-- ============================================================
-- Categorize existing stock_items (one-off data fix, not a schema
-- migration). Matches by name within your org.
-- ============================================================

UPDATE stock_items si
SET category = v.category, updated_at = NOW()
FROM (VALUES
  ('Agave Syrup', 'DRY'),
  ('Almond Milk', 'DAI'),
  ('American Cheese', 'DAI'),
  ('American Mustard', 'DRY'),
  ('Apple Guava Juice', 'BEV'),
  ('Avos', 'PHF'),
  ('Baby Cos Gem', 'PHF'),
  ('Bacon Streaky', 'PTN'),
  ('Baking Paper', 'PCK'),
  ('Balsamic Glaze', 'DRY'),
  ('Balsamic Vinegar', 'DRY'),
  ('Banana Puree', 'FZN'),
  ('Basil', 'PHF'),
  ('Bbq Sauce', 'DRY'),
  ('Bin Bags', 'CLN'),
  ('Black Sesame', 'DRY'),
  ('Boss Coffee - Iced Double Espresso', 'BEV'),
  ('Boss Coffee - Iced Latte', 'BEV'),
  ('Boss Coffee - Iced Long Black', 'BEV'),
  ('Bounce Protein Ball - Cashew Caramel', 'SNK'),
  ('Bounce Protein Ball - Peanut', 'SNK'),
  ('Brie', 'DAI'),
  ('Brown Onion', 'PHF'),
  ('Bundaberg Ginger Beer', 'BEV'),
  ('Butter', 'DAI'),
  ('Button Mushroom', 'PHF'),
  ('Caneleni Beans', 'DRY'),
  ('Canned Chickpeas (Big)', 'DRY'),
  ('Canned Chickpeas (Small)', 'DRY'),
  ('Caramel Syrup', 'DRY'),
  ('Carmans Oat Slice - Choc Brownie', 'SNK'),
  ('Carmans Oat Slice - Cranberry', 'SNK'),
  ('Carrots', 'PHF'),
  ('Celery', 'PHF'),
  ('Chai Powder', 'DRY'),
  ('Cherry Toms', 'PHF'),
  ('Chia Seeds', 'DRY'),
  ('Chicken Breast', 'PTN'),
  ('Chilli Jam', 'DRY'),
  ('Chilli Powder', 'DRY'),
  ('Chives', 'PHF'),
  ('Chobani Pouch Blueberry', 'DAI'),
  ('Chobani Pouch Strawberry', 'DAI'),
  ('Choc Powder', 'DRY'),
  ('Chux', 'CLN'),
  ('Cinnamon Sugar', 'DRY'),
  ('Cling Wrap', 'PCK'),
  ('Cocobella Chocolate', 'BEV'),
  ('Coconut Chips', 'DRY'),
  ('Coconut Cream', 'DRY'),
  ('Coconut Milk', 'DRY'),
  ('Coke', 'BEV'),
  ('Coke Zero', 'BEV'),
  ('Coriander', 'PHF'),
  ('Crispy Shallot', 'DRY'),
  ('Cucumber', 'PHF'),
  ('Curry Powder', 'DRY'),
  ('Diet Coke', 'BEV'),
  ('Dijon', 'DRY'),
  ('Dill', 'PHF'),
  ('Dish Washing Liquid', 'CLN'),
  ('Eggs', 'DAI'),
  ('Fennel Seeds', 'DRY'),
  ('Fetta', 'DAI'),
  ('Flaky Salt', 'DRY'),
  ('Floor Cleaner', 'CLN'),
  ('Foil', 'PCK'),
  ('Frozen Berries', 'FZN'),
  ('Frozen Mango', 'FZN'),
  ('Full Cream Milk', 'DAI'),
  ('Garlic Granules', 'DRY'),
  ('Garlic Powder', 'DRY'),
  ('Gloves', 'CLN'),
  ('Goji Berries', 'DRY'),
  ('Grated Parmesan', 'DAI'),
  ('Green Cabbage', 'PHF'),
  ('Green Capsicum', 'PHF'),
  ('Ham Shaved', 'PTN'),
  ('Hand Soap', 'CLN'),
  ('Honey', 'DRY'),
  ('Horseradish', 'DRY'),
  ('Ice', 'FZN'),
  ('Jalapenos', 'DRY'),
  ('Kale', 'PHF'),
  ('Kettle Chips - Chilli', 'SNK'),
  ('Kettle Chips - Sea Salt', 'SNK'),
  ('Killer Pythons', 'SNK'),
  ('Leek', 'PHF'),
  ('Lemon', 'PHF'),
  ('Maple Syrup', 'DRY'),
  ('Matcha', 'DRY'),
  ('Mayo', 'DRY'),
  ('Milo', 'DRY'),
  ('Mint', 'PHF'),
  ('Muesli', 'DRY'),
  ('Napkins', 'PCK'),
  ('Nutella', 'DRY'),
  ('Oat Milk', 'DAI'),
  ('Olive Oil - Extra Virgin', 'DRY'),
  ('Onion Flakes', 'DRY')
) AS v(name, category)
WHERE si.name = v.name
  AND si.org_id = (
    SELECT om.org_id FROM org_members om
    JOIN auth.users u ON u.id = om.user_id
    WHERE u.email = 'clark@itsrecess.com.au' LIMIT 1
  );

-- Verify: anything still uncategorized?
SELECT name FROM stock_items
WHERE category IS NULL
  AND org_id = (SELECT om.org_id FROM org_members om JOIN auth.users u ON u.id = om.user_id WHERE u.email = 'clark@itsrecess.com.au' LIMIT 1)
ORDER BY name;
